apiVersion: batch/v1
kind: Job
metadata:
  generateName: flock-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: flock-notification
          image: curlimages/curl
          command:
            - "curl"
            - "-X"
            - "POST"
            - "https://api.flock.com/hooks/sendMessage/72c286de-9ade-47cc-8317-d0988a4958d6"
            - "-H"
            - "Content-Type: application/json"
            - "-d"
            - "{\"text\": \"Post-sync message.\"}"
      restartPolicy: onFailure
  backoffLimit: 2
